

cc_binary(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    deps = ["@libuv//:libuv-lib"],
)
cc_binary(
    name = "old",
    srcs = [
        "old.cpp",
    ],
)
cc_binary(
    name = "lwip-bin",
    srcs = [
        "lwip.cpp",
    ],
    deps = [
        "@lwip//:lwip"
    ],
)